
	NOLIST
; PICBASIC PRO(TM) Compiler 3.1.1.4, (c) 1997, 2018 ME Labs, Inc. All Rights Reserved. 

LABEL?L macro Label
        RST?RP
    ifdef PM_USED
        LALL
Label
        XALL
    else
Label
    endif
    endm

AIN?BBW macro Bin, Bout, Wndx
	MOVE?WA	Wndx
        addlw   low (Bout)
        movwf   FSR0L
	movlw	(Bout) >> 8
	addwfc	(Wndx) + 1, W
	movwf	FSR0H
        MOVE?BB Bin, INDF0
    endm

AIN?CBW macro Cin, Bout, Wndx
	MOVE?WA	Wndx
        addlw   low (Bout)
        movwf   FSR0L
	movlw	(Bout) >> 8
	addwfc	(Wndx) + 1, W
	movwf	FSR0H
        MOVE?CB Cin, INDF0
    endm

AOUT?BBB macro Bin, Bndx, Bout
        MOVE?BA Bndx
        addlw   low (Bin)
        movwf   FSR0L
	movlw	(Bin) >> 8
	clrf	FSR0H
	addwfc	FSR0H, F
        MOVE?BB INDF0, Bout
    endm

AOUT?BWB macro Bin, Wndx, Bout
        MOVE?WA Wndx
        addlw   low (Bin)
        movwf   FSR0L
	movlw	(Bin) >> 8
	addwfc	(Wndx) + 1, W
	movwf	FSR0H
        MOVE?BB INDF0, Bout
    endm

AOUT?TBT macro Regin, Bitin, Bndx, Regout, Bitout
        MOVE?CW Regin, FSR0L
        MOVE?BA Bndx
        addlw   Bitin
        L?CALL  ARRAYBIT
        CHK?RP  Regout
        btfsc   STATUS, Z
        bcf     Regout, Bitout
        btfss   STATUS, Z
        bsf     Regout, Bitout
    endm
ARRAYBIT_USED = 1

ADD?WBW macro Win, Bin, Wout
        MOVE?BA Bin
    if ((Wout) == (Win))
        CHK?RP  Wout
        addwf   Wout, F
	clrf	WREG
	addwfc	(Wout) + 1, F
    else
        CHK?RP  Win
        addwf   Win, W
        MOVE?AB Wout
        clrf    WREG
        CHK?RP  Win
        addwfc  (Win) + 1, W
        MOVE?AB (Wout) + 1
    endif
    endm

ADD?WCW macro Win, Cin, Wout
    if ((Wout) == (Win))
        CHK?RP  Wout
      if ((Cin) == 1)
        incf    Wout, F
      else  
        movlw   low (Cin)
        addwf   Wout, F
      endif
        movlw   (Cin) >> 8
        addwfc  (Wout) + 1, F
    else
        CHK?RP  Win
      if ((Cin) == 1)
        incf    Win, W
      else
        movlw   low (Cin)
        addwf   Win, W
      endif
        MOVE?AB Wout
        movlw   (Cin) >> 8
        CHK?RP  Win
        addwfc  (Win) + 1, W
        MOVE?AB (Wout) + 1
    endif
    endm

ADD?WWW macro Win1, Win2, Wout
    if ((Wout) == (Win1))
        MOVE?BA Win2
        CHK?RP  Wout
        addwf   Wout, F
        MOVE?BA (Win2) + 1
        CHK?RP  Wout
        addwfc  (Wout) + 1, F
    else
      if ((Wout) == (Win2))
        MOVE?BA Win1
        CHK?RP  Wout
        addwf   Wout, F
        MOVE?BA (Win1) + 1
        CHK?RP  Wout
        addwfc  (Wout) + 1, F
      else
        MOVE?BA Win1
        CHK?RP  Win2
        addwf   Win2, W
        MOVE?AB Wout
        MOVE?BA (Win1) + 1
        CHK?RP  Win2
        addwfc  (Win2) + 1, W
        MOVE?AB (Wout) + 1
      endif
    endif
    endm

DIV?BCB macro Bin, Cin, Bout
    if ((Cin) == 2)
        bcf     STATUS, C
      if ((Bout) == (Bin))
        CHK?RP  Bout
        rrcf    Bout, F
      else
        CHK?RP  Bin
        rrcf    Bin, W
        MOVE?AB Bout
      endif
    else
        MOVE?BW Bin, R0
        MOVE?CW Cin, R1
        L?CALL  DIV
        MOVE?AB Bout
    endif
    endm
DIV_USED = 1

DIV?WCB macro Win, Cin, Bout
    if ((Cin) == 2)
        CHK?RP  Win
        rrcf    (Win) + 1, W
        rrcf    Win, W
        MOVE?AB Bout
    else
        MOVE?WW Win, R0
        MOVE?CW Cin, R1
        L?CALL  DIV
        MOVE?AB Bout
    endif
    endm
DIV_USED = 1

DIV?WWW macro Win1, Win2, Wout
        MOVE?WW Win1, R0
        MOVE?WW Win2, R1
        L?CALL  DIV
        MOVE?AWW R0, Wout
    endm
DIV_USED = 1

MOD?BCB macro Bin, Cin, Bout
        MOVE?BW Bin, R0
        MOVE?CW Cin, R1
        L?CALL  DIV
        MOVE?BB R2, Bout
    endm
DIV_USED = 1

MOD?WCB macro Win, Cin, Bout
        MOVE?WW Win, R0
        MOVE?CW Cin, R1
        L?CALL  DIV
        MOVE?BB R2, Bout
    endm
DIV_USED = 1

MOD?WCW macro Win, Cin, Wout
        MOVE?WW Win, R0
        MOVE?CW Cin, R1
        L?CALL  DIV
        MOVE?WW R2, Wout
    endm
DIV_USED = 1

MOD?WWW macro Win1, Win2, Wout
        MOVE?WW Win1, R0
        MOVE?WW Win2, R1
        L?CALL  DIV
        MOVE?WW R2, Wout
    endm
DIV_USED = 1

MUL?BCW macro Bin, Cin, Wout
        MOVE?BW Bin, R3
        MOVE?CW Cin, R1
        L?CALL  MUL
        MOVE?AWW R2, Wout
    endm
MUL_USED = 1

MUL?WCW macro Win, Cin, Wout
        MOVE?WW Win, R3
        MOVE?CW Cin, R1
        L?CALL  MUL
        MOVE?AWW R2, Wout
    endm
MUL_USED = 1

SUB?CWW macro Cin, Win, Wout
        MOVE?BA Win
        sublw   low (Cin)
        MOVE?AB Wout
        movlw  	(Cin) >> 8
        CHK?RP	Win
        subfwb	(Win) + 1, W
        MOVE?AB (Wout) + 1
    endm

SUB?WCW macro Win, Cin, Wout
    if ((Wout) == (Win))
      if ((Cin) == 1)
        CHK?RP  Wout
        decf    Wout, F
      else
        movlw   low (Cin)
        CHK?RP  Wout
        subwf   Wout, F
      endif
        movlw   (Cin) >> 8
        subwfb	(Wout) + 1, F
    else
      if ((Cin) == 1)
        CHK?RP  Win
        decf    Win, W
      else
        movlw   low (Cin)
        CHK?RP  Win
        subwf   Win, W
      endif
        MOVE?AB Wout
        movlw   (Cin) >> 8
        CHK?RP  Win
        subwfb	(Win) + 1, W
        MOVE?AB (Wout) + 1
    endif
    endm

LAND?BBW macro Bin1, Bin2, Wout
        MOVE?BB Bin1, R0
        MOVE?BA Bin2
        L?CALL  LAND
        MOVE?AB Wout
        movwf   Wout + 1
    endm
LAND_USED = 1

LAND?WBW macro Win, Bin, Wout
        MOVE?BA Win
        iorwf   Win + 1, W
        movwf   R0
        MOVE?BA Bin
        L?CALL  LAND
        MOVE?AB Wout
        movwf   Wout + 1
    endm
LAND_USED = 1

LOR?BBW macro Bin1, Bin2, Wout
        MOVE?BB Bin1, R0
        MOVE?BA Bin2
        L?CALL  LOR
        MOVE?AB Wout
        movwf   Wout + 1
    endm
LOR_USED = 1

CMPF?WL macro Win, Label
        CLRWDT?
        MOVE?BA Win
        iorwf   (Win) + 1, W
        BIT?GOTO 1, STATUS, Z, Label
    endm

CMPEQ?BCB macro Bin, Cin, Bout
    if (((Cin) > -100h) & ((Cin) < 100h))
        MOVE?BA Bin
        sublw   Cin
	btfss	STATUS, Z
	setf	WREG
	xorlw	0ffh
        MOVE?AB Bout
    else
        CHK?RP  Bout
        clrf    Bout
    endif
    endm

CMPEQ?TCB macro Regin, Bitin, Cin, Bout
    if (((Cin) == 0) | ((Cin) == 1))
	clrf	WREG
	CHK?RP	Regin
      if ((Cin) == 0)
	btfss Regin, Bitin
      else
	btfsc Regin, Bitin
      endif
	setf	WREG
        MOVE?AB Bout
    else
        CHK?RP  Bout
        clrf    Bout
    endif
    endm

CMPEQ?WCB macro Win, Cin, Bout
    if (((Cin) > -10000h) & ((Cin) < 10000h))
        MOVE?WW Win, R0
        MOVE?CB (Cin) >> 8, R1 + 1
        MOVE?CA low (Cin)
        L?CALL  CMPEQ
        MOVE?AB Bout
    else
        CHK?RP  Bout
        clrf    Bout
    endif
    endm
CMPEQ_USED = 1

CMPEQ?WWB macro Win1, Win2, Bout
        MOVE?WW Win1, R0
        MOVE?WWA Win2, R1
        L?CALL  CMPEQ
        MOVE?AB Bout
    endm
CMPEQ_USED = 1

CMPEQ?CCL macro Cin1, Cin2, Label
    if ((Cin1) == (Cin2))
        L?GOTO  Label
    endif
    endm

CMPEQ?TCL macro Regin, Bitin, Cin, Label
    if (((Cin) == 0) | ((Cin) == 1))
        CLRWDT?
        BIT?GOTO Cin, Regin, Bitin, Label
    endif
    endm

CMPGE?WCL macro Win, Cin, Label
    if ((Cin) <= 0)
        L?GOTO  Label
    else
      if ((Cin) < 10000h)
        MOVE?WW Win, R0
        MOVE?CB (Cin) >> 8, R1 + 1
        MOVE?CA low (Cin)
        L?CALL  CMPGE
        BIT?GOTO 0, STATUS, Z, Label
      endif
    endif
    endm
CMPGE_USED = 1

CMPGT?BCL macro Bin, Cin, Label
    if ((Cin) < 0)
        L?GOTO  Label
    else
      if ((Cin) < 0ffh)
        CLRWDT?
        MOVE?CA (Cin) + 1
        CHK?RP  Bin
        subwf   Bin, W
        BIT?GOTO 1, STATUS, C, Label
      endif
    endif
    endm

CMPGT?WBL macro Win, Bin, Label
        MOVE?WW Win, R0
        MOVE?BA Bin
        L?CALL  CMPGTW
        BIT?GOTO 0, STATUS, Z, Label
    endm
CMPGTW_USED = 1

CMPGT?WCL macro Win, Cin, Label
    if ((Cin) < 0)
        L?GOTO  Label
    else
      if ((Cin) < 0ffffh)
        MOVE?WW Win, R0
        MOVE?CB (Cin) >> 8, R1 + 1
        MOVE?CA low (Cin)
        L?CALL  CMPGT
        BIT?GOTO 0, STATUS, Z, Label
      endif
    endif
    endm
CMPGT_USED = 1

CMPGT?WWL macro Win1, Win2, Label
        MOVE?WW Win1, R0
        MOVE?WWA Win2, R1
        L?CALL  CMPGT
        BIT?GOTO 0, STATUS, Z, Label
    endm
CMPGT_USED = 1

CMPLE?WCL macro Win, Cin, Label
    if ((Cin) >= 0ffffh)
        L?GOTO  Label
    else
      if ((Cin) >= 0)
        MOVE?WW Win, R0
        MOVE?CB (Cin) >> 8, R1 + 1
        MOVE?CA low (Cin)
        L?CALL  CMPLE
        BIT?GOTO 0, STATUS, Z, Label
      endif
    endif
    endm
CMPLE_USED = 1

CMPLT?WWB macro Win1, Win2, Bout
        MOVE?WW Win1, R0
        MOVE?WWA Win2, R1
        L?CALL  CMPLT
        MOVE?AB Bout
    endm
CMPLT_USED = 1

CMPLT?WCL macro Win, Cin, Label
    if ((Cin) >= 10000h)
        L?GOTO  Label
    else
      if ((Cin) > 0)
        MOVE?WW Win, R0
        MOVE?CB (Cin) >> 8, R1 + 1
        MOVE?CA low (Cin)
        L?CALL  CMPLT
        BIT?GOTO 0, STATUS, Z, Label
      endif
    endif
    endm
CMPLT_USED = 1

CMPNE?BCL macro Bin, Cin, Label
    if (((Cin) > -100h) & ((Cin) < 100h))
        CLRWDT?
        MOVE?BA Bin
        sublw   Cin
        BIT?GOTO 0, STATUS, Z, Label
    else
        L?GOTO  Label
    endif
    endm

CMPNE?CCL macro Cin1, Cin2, Label
    if ((Cin1) != (Cin2))
        L?GOTO  Label
    endif
    endm

CMPNE?TCL macro Regin, Bitin, Cin, Label
    if ((Cin) == 0)
        CLRWDT?
        BIT?GOTO 1, Regin, Bitin, Label
    else
      if ((Cin) == 1)
        CLRWDT?
        BIT?GOTO 0, Regin, Bitin, Label
      else
        L?GOTO  Label
      endif
    endif
    endm

CMPNE?WCL macro Win, Cin, Label
    if (((Cin) > -10000h) & ((Cin) < 10000h))
        MOVE?CW	Cin, R0
        MOVE?WWA Win, R1
        L?CALL  CMPNE
        BIT?GOTO 0, STATUS, Z, Label
    else
        L?GOTO  Label
    endif
    endm
CMPNE_USED = 1

DISABLE? macro
    endm

ENABLE? macro
    endm

GOSUB?L macro Label
    local dlabel
    ifdef DEBUG_STACK
        CHK?RP  DEBUG_STACK
      ifdef DEBUG_STACK_ADDR
        bcf     STATUS, C
        rlcf    DEBUG_STACK, W
        addlw   DEBUG_STACK_ADDR
        movwf   FSR0L
        clrf    FSR0H
        movlw   low (dlabel)
        movwf   POSTINC0
        movlw   high (dlabel)
        movwf   INDF0
      endif
        incf    DEBUG_STACK, F
    endif
        L?CALL  Label
dlabel
    endm

GOTO?L macro Label
        L?GOTO  Label
    endm

ICALL?L macro Label
        L?CALL  Label
    endm

INPUT?T macro Regin, Bitin
        MOVE?CT 1, ((Regin) + 12h), Bitin
    endm

NAP?C macro Cin
	sleep
    endm

NEXT?BCL macro Bin, Cin, Label
    if ((Cin) == 1)
        CHK?RP  Bin
        incf    Bin, F
    else
        movlw	Cin
        CHK?RP  Bin
        addwf   Bin, F
    endif
    if ((Cin) <= 255)
        BIT?GOTO 0, STATUS, C, Label
    endif
    endm

NEXT?WCL macro Win, Cin, Label
    if ((Cin) == 1)
        CHK?RP  Win
        incf    Win, F
    else  
        movlw   low (Cin)
        CHK?RP  Win
        addwf   Win, F
    endif
        movlw   (Cin) >> 8
        addwfc  (Win) + 1, F
    if ((Cin) <= 65535)
        BIT?GOTO 0, STATUS, C, Label
    endif
    endm

NEXTM?WCL macro Win, Cin, Label
    if ((Cin) == 1)
        CHK?RP  Win
        decf	Win, F
    else
        movlw   low (Cin)
        CHK?RP  Win
        subwf   Win, F
    endif
        movlw   (Cin) >> 8
	subwfb	Win + 1, F
    if ((Cin) <= 65535)
        BIT?GOTO 1, STATUS, C, Label
    endif
    endm

ONINT?LL macro Inthand, Intchk
    local label
        bsf     INTCON, GIE
        bra     label
Intchk  btfsc   INTCON, GIE
        return
        L?GOTO  Inthand
label
    endm
ONINT_USED = 1

OUTPUT?T macro Regin, Bitin
        MOVE?CT 0, ((Regin) + 12h), Bitin
    endm

PAUSE?C macro Cin
    if (((Cin) >> 8) == 0)
        MOVE?CA Cin
        L?CALL  PAUSE
    else
        MOVE?CB (Cin) >> 8, R1 + 1
        MOVE?CA low (Cin)
        L?CALL  PAUSEL
    endif
    endm
PAUSE_USED = 1

PAUSEUS?C macro Cin
    if (((Cin) >> 8) == 0)
        movlw   Cin
        L?CALL  PAUSEUS
    else
        MOVE?CB (Cin) >> 8, R0 + 1
        MOVE?CA low (Cin)
        L?CALL  PAUSEUSL
    endif
    endm
PAUSEUS_USED = 1

READADDRESS?C macro Cin
    ifdef EEADRH
        MOVE?CW (Cin) & 0ffffh, EEADR
    else
        MOVE?CB Cin, EEADR
    endif
    endm

READW?W macro Wout
        L?CALL  READ
        MOVE?AB Wout
        L?CALL  READ
        MOVE?AB Wout + 1
    endm
READ_USED = 1

RESUME? macro
        RST?RP
        retfie
    endm

RETURN? macro
    ifdef DEBUG_STACK
        CHK?RP  DEBUG_STACK
        decf    DEBUG_STACK, F
    endif
        RST?RP
        return
    endm

SERMODE?C macro Cin
        MOVE?CB Cin, GOP
    endm

SERPIN?T macro Regin, Bitin
        BIT?R1  Regin, Bitin
    endm

SEROUT?C macro Cin
        movlw   Cin
        L?CALL  SEROUT
    endm
SEROUT_USED = 1

SEROUTD?B macro Bin
        MOVE?BA Bin
        L?CALL  SEROUTDEC
    endm
SEROUTDEC_USED = 1

SEROUTD?W macro Win
        MOVE?WWA Win, R2
        L?CALL  SEROUTDECL
    endm
SEROUTDEC_USED = 1

SERIN2DPIN?T macro Regin, Bitin
        BIT?R1  Regin, Bitin
    endm

SERIN2MODE?C macro Cin
        MOVE?CW Cin, R5
    endm

SERIN2COUNT?C macro Cin
        MOVE?CB Cin, R4 + 1
    endm

SERIN2TIME?C macro Cin
        MOVE?CW Cin, R6
    endm

SERIN2WAIT?CLL macro Cin, Label1, Label2
        L?CALL  SERIN2TO
        BIT?GOTO 0, STATUS, C, Label2
        sublw   Cin
        BIT?GOTO 0, STATUS, Z, Label1
    endm
SERIN2TO_USED = 1

SERIN2STR?BL macro Bin, Label
        MOVE?CW SERIN2TO, R8
	MOVE?CB	high (Bin), FSR2H
        MOVE?CA	low (Bin)
        L?CALL  SERIN2STR
        BIT?GOTO 0, STATUS, C, Label
    endm
SERIN2TO_USED = 1
SERIN2STR_USED = 1

WRITEADDRESS?C macro Cin
    ifdef EEADRH
        MOVE?CW (Cin) & 0ffffh, EEADR
    else
        MOVE?CB Cin, EEADR
    endif
    endm

WRITEW?W macro Win
        MOVE?BA Win
        L?CALL  WRITE
        MOVE?BA Win + 1
        L?CALL  WRITE
    endm
WRITE_USED = 1


	LIST
